### ISSUE TITLE
Status Messages

### ISSUE THREAD

**Issue by charlesnimo** [0akleytb/senior_design#9]
Instead of Reporting GPS Coordinates, Status Messages should be shown on the LCD Display. 
For example:

If no GPS fix, LCD display "No Satelite Fix"
If no microSD card detected, "Please insert microSD Card"
Brake Squeal button pressed ... "Brake Squeal Detected"
....
etc.

**Comment by 0akleytb** [comment]
Now, when you say "etc.", what do you mean?
Also, microSD card detection would involve another pin, but this is all do-able.
Some of these should also lock down certain parts of the program, stalling the program in the set-up and/or skipping parts of the loop code.
* If no SD card, then don't try to SD.open or dataFile.write
* If no satellite fix, then no data recording (I might could gray out the Start/Stop button)

**Comment by charlesnimo** [comment]
"etc" is used to indicate that further, similar items (status messages) could be implemented. The examples listed were just some of the few that came to mind.  

I agree that along with these status messages some parts of the program could be stalled and/or skipped.

The main idea is to make the User interface easier for FDP, provide some insight if for some reason they deviate away from how it is supposed to be used.

**Comment by 0akleytb** [comment]
No, I know what the term "etc" means in a general case; I was wondering what else you might have been thinking to put there.
And yes, I agree with this design goals for this issue.

**Comment by 0akleytb** [comment]
Replaced the GPS-reported coordinates and speed with Status section.
Precendence of error messages (so far) is as follows: 
* If no SD card, report error of no SD card, and wait for user to insert card
  * New hardware added to detect SD card at Digital Pin 49 (reflected in latest Drive schematic)
* Else, if no GPS fix, report error of no fix, and wait for fix
* Else, report no error, and print "Good!" along with GPS -reported time


Should the need arise for more varied error reporting, such messages can be brought up in another issue.
